# Generated by Django 3.2.18 on 2023-03-14 06:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_about_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
