# Generated by Django 3.2.18 on 2023-03-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_text_about_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='status',
        ),
        migrations.AlterField(
            model_name='about',
            name='post',
            field=models.CharField(max_length=500),
        ),
    ]
