# Generated by Django 3.2.18 on 2023-03-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20230314_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='post',
            field=models.TextField(),
        ),
    ]
